name: Delete Branches on PR Merge

on:
  pull_request:
    types: [closed]  # Triggers when a PR is closed

jobs:
  delete-branches:
    if: github.event.pull_request.merged == true && github.event.pull_request.base.ref == 'main'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Delete all branches except 'main'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git fetch --all
          for branch in $(git branch -r | grep -vE 'main|HEAD|master' | sed 's/origin\///'); do
            echo "Deleting branch $branch"
            git push origin --delete $branch
          done
